import Head from "next/head";
import { useEffect, useState } from "react";
import CreateTodoTextBar from "../components/CreateTodoTextBar";
import Todos from "../components/Todos";
// import Image from "next/image";

export default function Home() {
  const TODOS_URL = process.env.NODE_ENV === 'development' ? 'api/v1/todos' : 'https://full-stack-todo-app-server.herokuapp.com/api/v1/todosF';
  const [todos, setTodos] = useState([]);
  const [loading, setLoading] = useState(true);

  const getTodos = async () => {
    try {
      const response = await fetch(TODOS_URL);
      const data = await response.json();
      setTodos(data.data.todos)
      setLoading(false);
      console.log(data.data.todos)
    } catch (err) {
      console.log('Error!', err);
    }
  }

  useEffect(() => {
    getTodos();
    console.log(process.env.NODE_ENV)
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div>
        <h1>My todos</h1>
        <CreateTodoTextBar todos={todos} setTodos={setTodos} />
        {!loading && <Todos todos={todos} setTodos={setTodos} /> || <h2>Loading...</h2>}
      </div>
    </div>
  );
}
