import Head from "next/head";
import { useEffect, useState } from "react";
import CreateTodoTextBar from "../components/CreateTodoTextBar";
import Todos from "../components/Todos";
import { fetchTodos } from "../utils/manageTodosMethods";
// import Image from "next/image";

export default function Home() {
  const [todos, setTodos] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    console.log(process.env.NODE_ENV)
    fetchTodos().then((todos) => {
      setTodos(todos);
      setLoading(false);
    })
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div>
        <h1>My todos</h1>
        <CreateTodoTextBar todos={todos} setTodos={setTodos} />
        {!loading && <Todos todos={todos} setTodos={setTodos} /> || <h2>Loading...</h2>}
      </div>
    </div>
  );
}
